### ISSUE TITLE
How do I tell the user what the minimum requirement is?

### ISSUE THREAD

**Issue by wilsonf1** [ablanco/jquery.pwstrength.bootstrap#62]
I have a working example on my password field but I'm a bit unsure how I specifically tell the user how strong their password needs to be.

For instance, some websites say:

Minimum 6 characters
At least 1 upper case letter
At least 1 symbol

At the moment, I am just picking up the "data.score" and allowing the user to continue with saving their password so long as the score is above 38 (I have picked 38 out of thin air - what are the absolute scores that define what is medium, what is strong etc etc... - in truth I'm a bit unsure what I'm fully doing!

**Comment by ablanco** [comment]
Hi wilsonf1, you can find the default options values in [src/options.js](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/options.js). It's all documented [here](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/OPTIONS.md).

You can change any of those options. You can choose which rules are being applied (`rules.activated`) and their associated scores (`rules.scores`). Those two options are key to figure out what makes a good password for your site, so you can give proper advice to your users. It's also relevant the `ui.scores` that defines the frontier scores between the verdicts, you can change it as you consider better.

These are the default activated rules:

- wordNotEmail
- wordLength
- wordSimilarToUsername
- wordSequences
- wordLowercase
- wordUppercase
- wordOneNumber
- wordThreeNumbers
- wordOneSpecialChar
- wordTwoSpecialChar
- wordUpperLowerCombo
- wordLetterNumberCombo
- wordLetterNumberCharCombo

All of this rules add or subtract to the final score. So the general advice would be to have a long password that is not an email nor similar to your username, and that contains letters in different cases,  several numbers and several symbols. But because the rules keep adding every time they match is possible to get a great score with a password without numbers, just making it long enough for example.

I guess the conclusion is that there are no minimum requirements for a password to score high, just guidelines.

Also, if you don't like this scoring engine, you can use the [zxcvbn](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/) library to score the passwords.

Regards.

**Comment by wilsonf1** [comment]
Thank you for clarifying. I have tested this out of the box and the feedback from our employees is the security is just a bit too high with the default settings. 

I'm trying to think what the best modification would be. Would changing raisePower: 1.4 to 1.5 be a good idea?

**Comment by ablanco** [comment]
That options is used to score the password length.

Maybe you should change the `rules.scores` option itself. Move from `[14, 26, 38, 50]` to `[10, 20, 30, 40]` or similar. Lower the score needed to achieve the different verdicts. You can also deactivate rules.

Good luck.

**Comment by wilsonf1** [comment]
OK sounds good! Last thing - Is there any way I can change the "strong" background from orange to a different colour?

**Comment by ablanco** [comment]
It uses the bootstrap bar's classes: `"error", "warning", "success"`

You need to change the bootstrap variables to change the bar color for the `warning` class, if you want to make the change in the whole site. If you only want to change the warning progress bar in the password strength meter, I'm afraid you'll need to overwrite the bootstrap css rules with your own.

**Comment by wilsonf1** [comment]
Understood! Thank you!
