### ISSUE TITLE
How to change the colour of the progress bar for different verdicts?

### ISSUE THREAD

**Issue by tonyhogben** [ablanco/jquery.pwstrength.bootstrap#67]
Hi,

Great plugin. 

Is there a way to change the colour of the progress bar for each verdict? 

I would like to use 'warning' for the 2nd (normal) verdict reserving 'danger' for just the first (weak) verdict.

**Comment by ablanco** [comment]
Hi Tony.

The plugin doesn't support to personalize the css classes applied to the progress bar per verdict. But I think it would be a nice feature to have. I'll leave this issue opened to remind me to do it. Now I just need to find the time for it.

**Comment by ablanco** [comment]
Implemented in d2b7c52f75f74cd1e344ea27a0b4a643b6088c16

It will be available in the next release.

**Comment by tonyhogben** [comment]
Hi again,

I've just updated the plugin to version 1.2.9 (great work as ever) and I assume the new colorClasses option is the one you have added to cater for this requirement?

Am I correct in my assumption that there are only 3 items in the colorClasses array, yet there are 5 verdicts? How do I assign a different class for the "Weak" and "Normal" verdicts?

Thanks,

Tony.

**Comment by ablanco** [comment]
Hi Tony,
that is the option, yes. It only has three classes because I chose to use the three color scheme from bootstrap (red, yellow and green). 

The function that assigns the verdict and color based on the score is [here](https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/ui.js#L239). There you can see that verdicts 0 and 1 have the same color, 2 and 3 also share, and the last verdict 4 has the last color class. It wouldn't be hard to modify that function to allow a different class per verdict, I just never thought of it, but right now it does not allow to have 5 different colors.

**Comment by tonyhogben** [comment]
That's a shame as that is what my original question asked - how to use different colours for 'weak' and 'normal' as 'normal' suggests a password is okay and 'weak' suggests it is not, therefore it feels like they need visual separation.

**Comment by ablanco** [comment]
As a workaround you can change the verdicts texts, and change "Weak" into "Invalid" and "Normal" into "Weak", for example. But I'll add the possibility to have 5 different color classes.

**Comment by tonyhogben** [comment]
Thanks Alejandro.

**Comment by ablanco** [comment]
Implemented in d19629f291ad45174dbfe579c8ac8e29bd6cfd48

It will be available in the next release.
