### ISSUE TITLE
Width 0% on div.progress-bar when using 6 different numbers

### ISSUE THREAD

**Issue by arnoudhgz** [ablanco/jquery.pwstrength.bootstrap#70]
Hi,

When I use a password with six different numbers (e.g.: 123456) the div with class 'progress-bar' gets a width of 0%. This results in a text behind in stead of under the input field. See image below:

![knipsel](https://cloud.githubusercontent.com/assets/10864061/9493048/1c6642ec-4bfd-11e5-8223-ff2060d59da2.PNG)

**Comment by ablanco** [comment]
Hi. That's strange, I've never seen that behavior. But reviewing the code I found this: https://github.com/ablanco/jquery.pwstrength.bootstrap/blob/master/src/ui.js#L214

It should be a `<=` instead of `<` or, when the score hits zero, the bar is gonna be empty. And that's what I was trying to avoid.

But as I said, I've never seen the bar disappear and make the verdict move up. I don't know how to reproduce that. Could I bother you to set up a [jsfiddle](http://jsfiddle.net/) or similar with an example of that happening? It would help a lot.

Thanks.

**Comment by ablanco** [comment]
Cannot reproduce.
